mods.extendedcrafting.TableCrafting.addShaped(4, <modularmachinery:definer_three_sk_factory_controller>, [
	[<ore:blockCrystalMatrix>, <contenttweaker:neutronium_bombarder>, <modularmachinery:blockcasing>, <modularmachinery:blockcasing>, <modularmachinery:blockcasing>, <modularmachinery:blockcasing>, <modularmachinery:blockcasing>, <contenttweaker:neutronium_bombarder>, <ore:blockCrystalMatrix>], 
	[<contenttweaker:neutronium_bombarder>, <contenttweaker:brightseel_alloy_plate>, <contenttweaker:definer_casing>, <contenttweaker:definer_casing>, <contenttweaker:defined_ingot>, <contenttweaker:definer_casing>, <contenttweaker:definer_casing>, <contenttweaker:brightseel_alloy_plate>, <contenttweaker:neutronium_bombarder>], 
	[<modularmachinery:blockcasing>, <contenttweaker:definer_casing>, <contenttweaker:defined_plate>, <contenttweaker:defined_gear>, <contenttweaker:defined_engine>, <contenttweaker:defined_gear>, <contenttweaker:defined_plate>, <contenttweaker:definer_casing>, <modularmachinery:blockcasing>], 
	[<modularmachinery:blockcasing>, <contenttweaker:definer_casing>, <contenttweaker:defined_gear>, <contenttweaker:strange_matter_capsule>, <contenttweaker:defined_servo>, <contenttweaker:strange_matter_capsule>, <contenttweaker:defined_gear>, <contenttweaker:definer_casing>, <modularmachinery:blockcasing>], 
	[<modularmachinery:blockcasing>, <contenttweaker:defined_ingot>, <contenttweaker:defined_engine>, <contenttweaker:defined_servo>, <contenttweaker:defined_block>, <contenttweaker:defined_servo>, <contenttweaker:defined_engine>, <contenttweaker:defined_ingot>, <modularmachinery:blockcasing>], 
	[<modularmachinery:blockcasing>, <contenttweaker:definer_casing>, <contenttweaker:defined_gear>, <contenttweaker:strange_matter_capsule>, <contenttweaker:defined_servo>, <contenttweaker:strange_matter_capsule>, <contenttweaker:defined_gear>, <contenttweaker:definer_casing>, <modularmachinery:blockcasing>], 
	[<modularmachinery:blockcasing>, <contenttweaker:definer_casing>, <contenttweaker:defined_plate>, <contenttweaker:defined_gear>, <contenttweaker:defined_engine>, <contenttweaker:defined_gear>, <contenttweaker:defined_plate>, <contenttweaker:definer_casing>, <modularmachinery:blockcasing>], 
	[<contenttweaker:neutronium_bombarder>, <contenttweaker:brightseel_alloy_plate>, <contenttweaker:definer_casing>, <contenttweaker:definer_casing>, <contenttweaker:defined_ingot>, <contenttweaker:definer_casing>, <contenttweaker:definer_casing>, <contenttweaker:brightseel_alloy_plate>, <contenttweaker:neutronium_bombarder>], 
	[<ore:blockCrystalMatrix>, <contenttweaker:neutronium_bombarder>, <modularmachinery:blockcasing>, <modularmachinery:blockcasing>, <modularmachinery:blockcasing>, <modularmachinery:blockcasing>, <modularmachinery:blockcasing>, <contenttweaker:neutronium_bombarder>, <ore:blockCrystalMatrix>]
]);